pipeline {
	agent {
    node {
      label 'node-addons'
    }
  }
  environment {
     NODE_PATH = '/QOpenSys/pkgs/lib/nodejs20/bin'
  }
  stages {
    stage('build') {
      steps {
        sh '''
            export PATH=$NODE_PATH:$PATH
            npm i
            npm rebuild --verbose
        '''
      }
    }
    stage('create-gh-release') {
      when { buildingTag() }
      environment {
        GH_TOKEN = credentials('idb-connector-gh-token')
      }
      steps {
        sh '''
           export GITHUB_TOKEN=$GH_TOKEN_PSW
           export PATH=$NODE_PATH:$PATH
           node .github/create-release.js
        '''
      }
    }
  }
}
